In [5]:
import pandas as pd
df =pd.read_csv('import_csv/85_Imp_Jul-21.csv', encoding = "ISO-8859-1")
code = [85414011,85414012]
df = df[df['HS_CODE'].isin(code)]

/home/abhishek/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (27,32,33) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [6]:

df.to_csv('output/11-aug-1.csv')

In [7]:
df = df[(df['UNIT_PRICE_USD'] >= 50)]
df.to_csv('output/11-aug-2.csv')

In [8]:
wp_range = list(range(300,600,5))
WP = list(range(300,600,5))
WP = list(map(str, WP))
wp1 = pd.concat([df['PRODUCT_DESCRIPTION'].str.extract('(?P<WP>{})'.format("|".join(WP)), expand=True).fillna('0')], axis=1)
df['wp']= wp1
df['IMP_DATE'] = pd.to_datetime(df['IMP_DATE'], format='%d-%b-%y')
df

,CUSH,INDIAN_PORT,BE_NO,IMP_DATE,IEC,IMPORTER_NAME,ADDRESS,CITY,CHA_NO,CHA_NAME,...,INVOICE_UNITPRICE_FC,TYPE,INVOICE_NO,IEC_PIN,PHONE_NO,EMAIL,CONTACT_PERSON,LANDING_PORT_CODE,LANDING_PORT_NAME,wp
801,INNSA1,Nhava Sheva Sea,4519993,2021-07-01,AATFP3501G,PHOTOVOLTAIC SOLAR,"33, SURYA VALLEY, BAKROL ROAD, BAKROL","ANAND, GUJARAT",AABCV9169RCH001,VENUS CONTAINER LINE LOGISTICS PVT LTD,...,123.715000,H,NaN,388315.0,'918866488000,info@photovoltaicsolar.in,JAY THAKKAR,NaN,NaN,545
1323,INNSA1,Nhava Sheva Sea,4524279,2021-07-01,515908207,ORNATE AGENCIES PRIVATE LIMITED,"G-14 ARUNACHAL BUILDING, BARAKHAMBAROAD","NEW DELHI, DELHI",AADCT2654FCH003,TRANSLOG EXPRESS PVT LTD,...,103.500000,W,NaN,110001.0,'919910173481,anisha@ornatesolar.com,JAGDISH GOEL,NaN,NaN,450
1324,INNSA1,Nhava Sheva Sea,4524279,2021-07-01,515908207,ORNATE AGENCIES PRIVATE LIMITED,"G-14 ARUNACHAL BUILDING, BARAKHAMBAROAD","NEW DELHI, DELHI",AADCT2654FCH003,TRANSLOG EXPRESS PVT LTD,...,103.500000,W,NaN,110001.0,'919910173481,anisha@ornatesolar.com,JAGDISH GOEL,NaN,NaN,450
1325,INNSA1,Nhava Sheva Sea,4524279,2021-07-01,515908207,ORNATE AGENCIES PRIVATE LIMITED,"G-14 ARUNACHAL BUILDING, BARAKHAMBAROAD","NEW DELHI, DELHI",AADCT2654FCH003,TRANSLOG EXPRESS PVT LTD,...,103.500000,W,NaN,110001.0,'919910173481,anisha@ornatesolar.com,JAGDISH GOEL,NaN,NaN,450
1350,INNSA1,Nhava Sheva Sea,4524279,2021-07-01,515908207,ORNATE AGENCIES PRIVATE LIMITED,"G-14 ARUNACHAL BUILDING, BARAKHAMBAROAD","NEW DELHI, DELHI",AADCT2654FCH003,TRANSLOG EXPRESS PVT LTD,...,103.500000,W,NaN,110001.0,'919910173481,anisha@ornatesolar.com,JAGDISH GOEL,NaN,NaN,450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
680296,INNSA1,Nhava Sheva Sea,4889445,2021-07-31,307041743,TWINCITY SUNLIFE PRIVATE LIMITED,"22-2, EVERGREEN IND.ESTATE, SHAKTI MILL LANE, ...",MUMBAI-MS,NaN,NaN,...,119.977007,H,NaN,400011.0,'24954596,info@twincity.co.in,"MR. BHUNESH CHANDRA,MR. PREM PRAKASH CHANDRA",NaN,NaN,470
682503,INMAA1,Chennai Sea,4890412,2021-07-31,401000044,VISNUKUMAR TRADERS PRIVATE LIMITED,28A PADUR MAIN ROAD KUTHAMBAKKAM,"CHENNAI TAMILNADU, TAMIL NADU",AACCN7806NCH001,NTC LOGISTICS INDIA PRIVATE LIMITED,...,102.150000,H,NaN,600124.0,'918754493715,dox@vktpl.com,P.VISHNUKUMAR,NaN,NaN,450
699389,INBGK6,Bhagat ki Kothi - Jodhpur ICD,4881069,2021-07-31,AAHCR7973H,RENEW SOLAR ENERGY JHARKHAND ONE PRIVATE LIMITED,138 ANSAL CHAMBER-II BHIKAJI CAM A PLACE,"NEW DELHI, DELHI",NaN,NaN,...,104.420000,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,460
699986,INDER6,Noida-Dadri (ICD),4887471,2021-07-31,AAHCD3809N,DS SMART ENERGY PRIVATE LIMITED,"BLOCK- TARIKHET, DS SMART ENERGY PR",ALMORA,AAIPJ9707FCH001,M/S PARSHVNATH CLEARING AND FORWARDING AGENCY,...,123.930000,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,540
701446,INMUN1,Mundra Sea,4888413,2021-07-31,712029401,SUNTROP SOLAR PRIVATE LIMITED,"NEW NO-31, 9TH MAIN, 4TH CROSS, RPCLAYOUT, VIJ...","BNGLORE, KRNTK",NaN,NaN,...,98.400000,H,NaN,560040.0,'919886301150,ccounts.blr@islf.in,"NARENDRADUTT DATTATREY KOLLUR,D.TAMMANNAPPA KO...",NaN,NaN,410

In [9]:
df['SUPPLIER_NAME'] = df['SUPPLIER_NAME'].str.replace('[^\w\s]','')
df['IMPORTER_NAME'] = df['IMPORTER_NAME'].str.replace('[^\w\s]','')
d1 = pd.read_csv('shipper/supplier_aug_11.csv')
d1['name'] = d1['name'].str.replace('[^\w\s]','')
d11= pd.Series(d1.id.values,index=d1.name).to_dict()
df['supplier_id'] = df['SUPPLIER_NAME'].map(d11)

In [10]:
df

,CUSH,INDIAN_PORT,BE_NO,IMP_DATE,IEC,IMPORTER_NAME,ADDRESS,CITY,CHA_NO,CHA_NAME,...,TYPE,INVOICE_NO,IEC_PIN,PHONE_NO,EMAIL,CONTACT_PERSON,LANDING_PORT_CODE,LANDING_PORT_NAME,wp,supplier_id
801,INNSA1,Nhava Sheva Sea,4519993,2021-07-01,AATFP3501G,PHOTOVOLTAIC SOLAR,"33, SURYA VALLEY, BAKROL ROAD, BAKROL","ANAND, GUJARAT",AABCV9169RCH001,VENUS CONTAINER LINE LOGISTICS PVT LTD,...,H,NaN,388315.0,'918866488000,info@photovoltaicsolar.in,JAY THAKKAR,NaN,NaN,545,1062.0
1323,INNSA1,Nhava Sheva Sea,4524279,2021-07-01,515908207,ORNATE AGENCIES PRIVATE LIMITED,"G-14 ARUNACHAL BUILDING, BARAKHAMBAROAD","NEW DELHI, DELHI",AADCT2654FCH003,TRANSLOG EXPRESS PVT LTD,...,W,NaN,110001.0,'919910173481,anisha@ornatesolar.com,JAGDISH GOEL,NaN,NaN,450,603.0
1324,INNSA1,Nhava Sheva Sea,4524279,2021-07-01,515908207,ORNATE AGENCIES PRIVATE LIMITED,"G-14 ARUNACHAL BUILDING, BARAKHAMBAROAD","NEW DELHI, DELHI",AADCT2654FCH003,TRANSLOG EXPRESS PVT LTD,...,W,NaN,110001.0,'919910173481,anisha@ornatesolar.com,JAGDISH GOEL,NaN,NaN,450,603.0
1325,INNSA1,Nhava Sheva Sea,4524279,2021-07-01,515908207,ORNATE AGENCIES PRIVATE LIMITED,"G-14 ARUNACHAL BUILDING, BARAKHAMBAROAD","NEW DELHI, DELHI",AADCT2654FCH003,TRANSLOG EXPRESS PVT LTD,...,W,NaN,110001.0,'919910173481,anisha@ornatesolar.com,JAGDISH GOEL,NaN,NaN,450,603.0
1350,INNSA1,Nhava Sheva Sea,4524279,2021-07-01,515908207,ORNATE AGENCIES PRIVATE LIMITED,"G-14 ARUNACHAL BUILDING, BARAKHAMBAROAD","NEW DELHI, DELHI",AADCT2654FCH003,TRANSLOG EXPRESS PVT LTD,...,W,NaN,110001.0,'919910173481,anisha@ornatesolar.com,JAGDISH GOEL,NaN,NaN,450,603.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
680296,INNSA1,Nhava Sheva Sea,4889445,2021-07-31,307041743,TWINCITY SUNLIFE PRIVATE LIMITED,"22-2, EVERGREEN IND.ESTATE, SHAKTI MILL LANE, ...",MUMBAI-MS,NaN,NaN,...,H,NaN,400011.0,'24954596,info@twincity.co.in,"MR. BHUNESH CHANDRA,MR. PREM PRAKASH CHANDRA",NaN,NaN,470,879.0
682503,INMAA1,Chennai Sea,4890412,2021-07-31,401000044,VISNUKUMAR TRADERS PRIVATE LIMITED,28A PADUR MAIN ROAD KUTHAMBAKKAM,"CHENNAI TAMILNADU, TAMIL NADU",AACCN7806NCH001,NTC LOGISTICS INDIA PRIVATE LIMITED,...,H,NaN,600124.0,'918754493715,dox@vktpl.com,P.VISHNUKUMAR,NaN,NaN,450,1062.0
699389,INBGK6,Bhagat ki Kothi - Jodhpur ICD,4881069,2021-07-31,AAHCR7973H,RENEW SOLAR ENERGY JHARKHAND ONE PRIVATE LIMITED,138 ANSAL CHAMBER-II BHIKAJI CAM A PLACE,"NEW DELHI, DELHI",NaN,NaN,...,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,460,767.0
699986,INDER6,Noida-Dadri (ICD),4887471,2021-07-31,AAHCD3809N,DS SMART ENERGY PRIVATE LIMITED,"BLOCK- TARIKHET, DS SMART ENERGY PR",ALMORA,AAIPJ9707FCH001,M/S PARSHVNATH CLEARING AND FORWARDING AGENCY,...,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,540,1057.0
701446,INMUN1,Mundra Sea,4888413,2021-07-31,712029401,SUNTROP SOLAR PRIVATE LIMITED,"NEW NO-31, 9TH MAIN, 4TH CROSS, RPCLAYOUT, VIJ...","BNGLORE, KRNTK",NaN,NaN,...,H,NaN,560040.0,'919886301150,ccounts.blr@islf.in,"NARENDRADUTT DATTATREY KOLLUR,D.TAMMANNAPPA KO...",NaN,NaN,410,991.0

In [11]:
product = pd.read_csv('product/product_aug_11.csv')
product.head()

,id,name,power_rating,created_at,is_active,created_by_id,supplier_id,type_id
0,2,TSM-545DE19,545,2021-06-02 08:47:19.222269,1,1,1033,3
1,3,JKM400M-72H-V,400,2021-06-02 08:49:11.643988,1,1,786,3
2,4,TSM-450DE17M(II),450,2021-06-02 09:14:44.169680,1,1,1033,3
3,5,LR4-72HPH-450M,450,2021-06-03 03:48:12.235411,1,25,839,3
4,6,LR4-72HPH-450M,450,2021-06-03 03:49:15.444248,1,25,839,3

In [12]:
mode_name= product['name']

In [13]:
wp3 = pd.concat([df['PRODUCT_DESCRIPTION'].str.extract('(?P<mode_name>{})'.format("|".join(mode_name)), expand=True).fillna('0')], axis=1)

In [9]:
wp3

                  mode_name  1  2  3  4  5
81                        0  0  0  0  0  0
801                       0  0  0  0  0  0
813                       0  0  0  0  0  0
814                       0  0  0  0  0  0
1323                      0  0  0  0  0  0
...                     ... .. .. .. .. ..
691934                    0  0  0  0  0  0
699389                    0  0  0  0  0  0
699986                    0  0  0  0  0  0
700575                    0  0  0  0  0  0
701446  SPR-P3-410-COM-1500  0  0  0  0  0

[603 rows x 6 columns]

In [15]:
df['mode_name']= wp3['mode_name']

In [11]:
df.columns

Index(['CUSH', 'INDIAN_PORT', 'BE_NO', 'IMP_DATE', 'IEC', 'IMPORTER_NAME',
       'ADDRESS', 'CITY', 'CHA_NO', 'CHA_NAME', 'ORIGIN_COUNTRY', 'HS_CODE',
       'PRODUCT_DESCRIPTION', 'QUANTITY', 'UNIT', 'UNIT_VALUE_INR',
       'TOTAL_ASSESSABLE_VALUE_INR', 'UNIT_PRICE_USD', 'TOTAL_ASSESS_USD',
       'TOTAL_DUTY_PAID', 'APPRAISING_GROUP', 'PORT_OF_SHIPMENT',
       'INVOICE_CURRENCY', 'SUPPLIER_NAME', 'SUPPLIER_ADDRESS',
       'INVOICE_UNITPRICE_FC', 'TYPE', 'INVOICE_NO', 'IEC_PIN', 'PHONE_NO',
       'EMAIL', 'CONTACT_PERSON', 'LANDING_PORT_CODE', 'LANDING_PORT_NAME',
       'wp', 'supplier_id', 'mode_name'],
      dtype='object')

In [16]:



p11= pd.Series(product.id.values,index=product.name).to_dict()
df['import_product_id'] = df['mode_name'].map(d11)
df = df.drop(columns=['mode_name'])

In [17]:
df

,CUSH,INDIAN_PORT,BE_NO,IMP_DATE,IEC,IMPORTER_NAME,ADDRESS,CITY,CHA_NO,CHA_NAME,...,INVOICE_NO,IEC_PIN,PHONE_NO,EMAIL,CONTACT_PERSON,LANDING_PORT_CODE,LANDING_PORT_NAME,wp,supplier_id,import_product_id
801,INNSA1,Nhava Sheva Sea,4519993,2021-07-01,AATFP3501G,PHOTOVOLTAIC SOLAR,"33, SURYA VALLEY, BAKROL ROAD, BAKROL","ANAND, GUJARAT",AABCV9169RCH001,VENUS CONTAINER LINE LOGISTICS PVT LTD,...,NaN,388315.0,'918866488000,info@photovoltaicsolar.in,JAY THAKKAR,NaN,NaN,545,1062.0,NaN
1323,INNSA1,Nhava Sheva Sea,4524279,2021-07-01,515908207,ORNATE AGENCIES PRIVATE LIMITED,"G-14 ARUNACHAL BUILDING, BARAKHAMBAROAD","NEW DELHI, DELHI",AADCT2654FCH003,TRANSLOG EXPRESS PVT LTD,...,NaN,110001.0,'919910173481,anisha@ornatesolar.com,JAGDISH GOEL,NaN,NaN,450,603.0,NaN
1324,INNSA1,Nhava Sheva Sea,4524279,2021-07-01,515908207,ORNATE AGENCIES PRIVATE LIMITED,"G-14 ARUNACHAL BUILDING, BARAKHAMBAROAD","NEW DELHI, DELHI",AADCT2654FCH003,TRANSLOG EXPRESS PVT LTD,...,NaN,110001.0,'919910173481,anisha@ornatesolar.com,JAGDISH GOEL,NaN,NaN,450,603.0,NaN
1325,INNSA1,Nhava Sheva Sea,4524279,2021-07-01,515908207,ORNATE AGENCIES PRIVATE LIMITED,"G-14 ARUNACHAL BUILDING, BARAKHAMBAROAD","NEW DELHI, DELHI",AADCT2654FCH003,TRANSLOG EXPRESS PVT LTD,...,NaN,110001.0,'919910173481,anisha@ornatesolar.com,JAGDISH GOEL,NaN,NaN,450,603.0,NaN
1350,INNSA1,Nhava Sheva Sea,4524279,2021-07-01,515908207,ORNATE AGENCIES PRIVATE LIMITED,"G-14 ARUNACHAL BUILDING, BARAKHAMBAROAD","NEW DELHI, DELHI",AADCT2654FCH003,TRANSLOG EXPRESS PVT LTD,...,NaN,110001.0,'919910173481,anisha@ornatesolar.com,JAGDISH GOEL,NaN,NaN,450,603.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
680296,INNSA1,Nhava Sheva Sea,4889445,2021-07-31,307041743,TWINCITY SUNLIFE PRIVATE LIMITED,"22-2, EVERGREEN IND.ESTATE, SHAKTI MILL LANE, ...",MUMBAI-MS,NaN,NaN,...,NaN,400011.0,'24954596,info@twincity.co.in,"MR. BHUNESH CHANDRA,MR. PREM PRAKASH CHANDRA",NaN,NaN,470,879.0,NaN
682503,INMAA1,Chennai Sea,4890412,2021-07-31,401000044,VISNUKUMAR TRADERS PRIVATE LIMITED,28A PADUR MAIN ROAD KUTHAMBAKKAM,"CHENNAI TAMILNADU, TAMIL NADU",AACCN7806NCH001,NTC LOGISTICS INDIA PRIVATE LIMITED,...,NaN,600124.0,'918754493715,dox@vktpl.com,P.VISHNUKUMAR,NaN,NaN,450,1062.0,NaN
699389,INBGK6,Bhagat ki Kothi - Jodhpur ICD,4881069,2021-07-31,AAHCR7973H,RENEW SOLAR ENERGY JHARKHAND ONE PRIVATE LIMITED,138 ANSAL CHAMBER-II BHIKAJI CAM A PLACE,"NEW DELHI, DELHI",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,460,767.0,NaN
699986,INDER6,Noida-Dadri (ICD),4887471,2021-07-31,AAHCD3809N,DS SMART ENERGY PRIVATE LIMITED,"BLOCK- TARIKHET, DS SMART ENERGY PR",ALMORA,AAIPJ9707FCH001,M/S PARSHVNATH CLEARING AND FORWARDING AGENCY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,540,1057.0,NaN
701446,INMUN1,Mundra Sea,4888413,2021-07-31,712029401,SUNTROP SOLAR PRIVATE LIMITED,"NEW NO-31, 9TH MAIN, 4TH CROSS, RPCLAYOUT, VIJ...","BNGLORE, KRNTK",NaN,NaN,...,NaN,560040.0,'919886301150,ccounts.blr@islf.in,"NARENDRADUTT DATTATREY KOLLUR,D.TAMMANNAPPA KO...",NaN,NaN,410,991.0,NaN

In [18]:
df.to_csv('output/11-aug-final.csv')

In [13]:
ok=df[['CUSH', 'INDIAN_PORT', 'BE_NO', 'IMP_DATE', 'IEC', 'IMPORTER_NAME',
       'ADDRESS', 'CITY', 'CHA_NO', 'CHA_NAME', 'ORIGIN_COUNTRY', 'HS_CODE',
       'PRODUCT_DESCRIPTION', 'QUANTITY', 'UNIT', 'UNIT_VALUE_INR',
       'TOTAL_ASSESSABLE_VALUE_INR', 'UNIT_PRICE_USD', 'TOTAL_ASSESS_USD',
       'TOTAL_DUTY_PAID', 'APPRAISING_GROUP', 'PORT_OF_SHIPMENT',
       'INVOICE_CURRENCY', 'SUPPLIER_NAME', 'SUPPLIER_ADDRESS',
       'INVOICE_UNITPRICE_FC', 'TYPE', 'INVOICE_NO', 'IEC_PIN', 'PHONE_NO',
       'EMAIL', 'CONTACT_PERSON', 'LANDING_PORT_CODE', 'LANDING_PORT_NAME']]

In [14]:
ok1=df[[ 'PRODUCT_DESCRIPTION','wp', 'supplier_id', 'import_product_id']]

In [19]:
ok1.to_csv("aug-10.csv" )

In [16]:
df.to_csv('may_total_2021.csv')

In [17]:
df =pd.read_csv('latest upload/2021.csv', encoding = "ISO-8859-1")
df1 =pd.read_csv('latest upload/2020.csv', encoding = "ISO-8859-1")
df2 =pd.read_csv('latest upload/2019.csv', encoding = "ISO-8859-1")

In [18]:
fd = pd.concat([df,df1,df2])
fd.to_csv('total.csv')