In [35]:
import pandas as pd
df =pd.read_csv('import_csv/85_Imp_Jun-21.csv', encoding = "ISO-8859-1")
code = [85414011,85414012]
df = df[df['HS_CODE'].isin(code)]
df.head()

/home/abhishek/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (27,32) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,CUSH,INDIAN_PORT,BE_NO,IMP_DATE,IEC,IMPORTER_NAME,ADDRESS,CITY,CHA_NO,CHA_NAME,...,SUPPLIER_ADDRESS,INVOICE_UNITPRICE_FC,TYPE,INVOICE_NO,IEC_PIN,PHONE_NO,EMAIL,CONTACT_PERSON,LANDING_PORT_CODE,LANDING_PORT_NAME
3949,INKKU6,Kanakpura - Jaipur ICD,4158719,1-Jun-21,AAACH4717Q,HASTI INDIA LIMITED,"4, NAVJEEVAN COMPLEX, JAIPUR",JAIPUR,AAJCS4801RCH001,SIDDHI VINAYAK CARGO PRIVATE LIMITED,...,"80 ROBINSON ROAD,NO.20-00, SINGAPORE 068898 SG",132.30,H,NaN,NaN,NaN,NaN,NaN,NaN,NULL\r
4064,INMUN1,Mundra Sea,4155773,1-Jun-21,390011711,TATA POWER SOLAR SYSTEMS LIMITED,"PLOT NO.78, ELECTRONIC CITYHOSUR ROAD","BANGALORE, KARNATAKA",AAACB0466ACH015,BABAJI SHIVRAM CLEARING AND CARRIERS PRIVATE L...,...,NaN,99.00,H,NaN,560100.0,'080-41194230,murgesp@tatabp.com,MR. RAMAKRISHNAN,NaN,NULL\r
4065,INMUN1,Mundra Sea,4156884,1-Jun-21,390011711,TATA POWER SOLAR SYSTEMS LIMITED,"PLOT NO.78, ELECTRONIC CITYHOSUR ROAD","BANGALORE, KARNATAKA",AAACB0466ACH015,BABAJI SHIVRAM CLEARING AND CARRIERS PRIVATE L...,...,NaN,99.00,H,NaN,560100.0,'080-41194230,murgesp@tatabp.com,MR. RAMAKRISHNAN,NaN,NULL\r
5326,INTKD6,Tughlakabad,4150911,1-Jun-21,514068850,RHINE SOLAR LIMITED,"A-75/4, IIND FLOORWAZIRPUR INDUSTRIAL AREA",NEW DELHI,AAECN2245HCH001,NIMIT CARGO MOVERS INDIA PRIVATE LIMITED,...,NaN,0.34,H,NaN,110052.0,'011-45092992,shiv@rhinesolar.in,SHIV MITTAL,NaN,NULL\r
5327,INTKD6,Tughlakabad,4150911,1-Jun-21,514068850,RHINE SOLAR LIMITED,"A-75/4, IIND FLOORWAZIRPUR INDUSTRIAL AREA",NEW DELHI,AAECN2245HCH001,NIMIT CARGO MOVERS INDIA PRIVATE LIMITED,...,NaN,0.36,H,NaN,110052.0,'011-45092992,shiv@rhinesolar.in,SHIV MITTAL,NaN,NULL\r

In [36]:
df

,CUSH,INDIAN_PORT,BE_NO,IMP_DATE,IEC,IMPORTER_NAME,ADDRESS,CITY,CHA_NO,CHA_NAME,...,SUPPLIER_ADDRESS,INVOICE_UNITPRICE_FC,TYPE,INVOICE_NO,IEC_PIN,PHONE_NO,EMAIL,CONTACT_PERSON,LANDING_PORT_CODE,LANDING_PORT_NAME
3949,INKKU6,Kanakpura - Jaipur ICD,4158719,1-Jun-21,AAACH4717Q,HASTI INDIA LIMITED,"4, NAVJEEVAN COMPLEX, JAIPUR",JAIPUR,AAJCS4801RCH001,SIDDHI VINAYAK CARGO PRIVATE LIMITED,...,"80 ROBINSON ROAD,NO.20-00, SINGAPORE 068898 SG",132.300000,H,NaN,NaN,NaN,NaN,NaN,NaN,NULL\r
4064,INMUN1,Mundra Sea,4155773,1-Jun-21,390011711,TATA POWER SOLAR SYSTEMS LIMITED,"PLOT NO.78, ELECTRONIC CITYHOSUR ROAD","BANGALORE, KARNATAKA",AAACB0466ACH015,BABAJI SHIVRAM CLEARING AND CARRIERS PRIVATE L...,...,NaN,99.000000,H,NaN,560100.0,'080-41194230,murgesp@tatabp.com,MR. RAMAKRISHNAN,NaN,NULL\r
4065,INMUN1,Mundra Sea,4156884,1-Jun-21,390011711,TATA POWER SOLAR SYSTEMS LIMITED,"PLOT NO.78, ELECTRONIC CITYHOSUR ROAD","BANGALORE, KARNATAKA",AAACB0466ACH015,BABAJI SHIVRAM CLEARING AND CARRIERS PRIVATE L...,...,NaN,99.000000,H,NaN,560100.0,'080-41194230,murgesp@tatabp.com,MR. RAMAKRISHNAN,NaN,NULL\r
5326,INTKD6,Tughlakabad,4150911,1-Jun-21,514068850,RHINE SOLAR LIMITED,"A-75/4, IIND FLOORWAZIRPUR INDUSTRIAL AREA",NEW DELHI,AAECN2245HCH001,NIMIT CARGO MOVERS INDIA PRIVATE LIMITED,...,NaN,0.340000,H,NaN,110052.0,'011-45092992,shiv@rhinesolar.in,SHIV MITTAL,NaN,NULL\r
5327,INTKD6,Tughlakabad,4150911,1-Jun-21,514068850,RHINE SOLAR LIMITED,"A-75/4, IIND FLOORWAZIRPUR INDUSTRIAL AREA",NEW DELHI,AAECN2245HCH001,NIMIT CARGO MOVERS INDIA PRIVATE LIMITED,...,NaN,0.360000,H,NaN,110052.0,'011-45092992,shiv@rhinesolar.in,SHIV MITTAL,NaN,NULL\r
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
666742,INNSA1,Nhava Sheva Sea,4514638,30-Jun-21,3111010457,ENRICH ENERGY PRIVATE LIMITED,"302, THE ORION, 3RD FLR., KOREGAON, PARK ROAD,...","PUNE, MHRSHTR",NaN,NaN,...,"80 ROBINSON ROAD,NO.20-00, SINGAPORE 068898 SG",125.895000,H,NaN,411001.0,'918605002352,sanjay.batheja@enrichenergy.com,"CHETAN ZAWAR,VIJAY ZAWAR",NaN,NULL\r
666743,INNSA1,Nhava Sheva Sea,4514638,30-Jun-21,3111010457,ENRICH ENERGY PRIVATE LIMITED,"302, THE ORION, 3RD FLR., KOREGAON, PARK ROAD,...","PUNE, MHRSHTR",NaN,NaN,...,"80 ROBINSON ROAD,NO.20-00, SINGAPORE 068898 SG",125.895000,H,NaN,411001.0,'918605002352,sanjay.batheja@enrichenergy.com,"CHETAN ZAWAR,VIJAY ZAWAR",NaN,NULL\r
667056,INNSA1,Nhava Sheva Sea,4511784,30-Jun-21,314012141,SEVEN GREENS SOLAR SYSTEMS PRIVATE LIMITED,"179 C 20 MIG COLONY OPP MHADA, OFFICE BANDRA EAST","MAHARASHTRA, MAHARASHTRA",NaN,NaN,...,"UNIT 1520,15/F, TOWER 2, GRAND CENTURY PLACE 1...",108.000000,H,NaN,400051.0,'919819137727,swapnil.padhye@7greens.in,PRADYOT BORKAR,NaN,NULL\r
667504,INNSA1,Nhava Sheva Sea,4509107,30-Jun-21,996000402,PREMIER ENERGIES LIMITED,"SY NO 54 PART, G.PULLA REDDY SWEETS, KAKAGUDA,...","SECUNDERBD, TELNGN",NaN,NaN,...,NaN,0.570000,H,NaN,500009.0,'919177001518,ramanjulu@premierenergies.com,"SALUJA SURENDERPAL SINGH,KESAR SINGH",NaN,NULL\r
671340,INFLT6,Falta Special Economic Zone (SEZ),1001118,30-Jun-21,205025056,VIKRAM SOLAR LIMITED,"FALTA SEZ, SECTOR- II24 PARAGANAS S",KOLKATA,NaN,NaN,...,NO 1 BEIJING ROAD ECONOMICDEVELOPMENT ZONE JIA...,1.626252,NULL,6000001942,743504.0,'919777451565,sujit.choudhury@vikramsolar.com,"JOGINDER PAL DUA,CHUNI LAL DUA",INCCU4,Kolkata Air Cargo\r

In [37]:
wp_range = list(range(300,600,5))
WP = list(range(300,600,5))
WP = list(map(str, WP))
wp1 = pd.concat([df['PRODUCT_DESCRIPTION'].str.extract('(?P<WP>{})'.format("|".join(WP)), expand=True).fillna('0')], axis=1)
df['wp']= wp1
df['IMP_DATE'] = pd.to_datetime(df['IMP_DATE'], format='%d-%b-%y')
df

,CUSH,INDIAN_PORT,BE_NO,IMP_DATE,IEC,IMPORTER_NAME,ADDRESS,CITY,CHA_NO,CHA_NAME,...,INVOICE_UNITPRICE_FC,TYPE,INVOICE_NO,IEC_PIN,PHONE_NO,EMAIL,CONTACT_PERSON,LANDING_PORT_CODE,LANDING_PORT_NAME,wp
3949,INKKU6,Kanakpura - Jaipur ICD,4158719,2021-06-01,AAACH4717Q,HASTI INDIA LIMITED,"4, NAVJEEVAN COMPLEX, JAIPUR",JAIPUR,AAJCS4801RCH001,SIDDHI VINAYAK CARGO PRIVATE LIMITED,...,132.300000,H,NaN,NaN,NaN,NaN,NaN,NaN,NULL\r,540
4064,INMUN1,Mundra Sea,4155773,2021-06-01,390011711,TATA POWER SOLAR SYSTEMS LIMITED,"PLOT NO.78, ELECTRONIC CITYHOSUR ROAD","BANGALORE, KARNATAKA",AAACB0466ACH015,BABAJI SHIVRAM CLEARING AND CARRIERS PRIVATE L...,...,99.000000,H,NaN,560100.0,'080-41194230,murgesp@tatabp.com,MR. RAMAKRISHNAN,NaN,NULL\r,455
4065,INMUN1,Mundra Sea,4156884,2021-06-01,390011711,TATA POWER SOLAR SYSTEMS LIMITED,"PLOT NO.78, ELECTRONIC CITYHOSUR ROAD","BANGALORE, KARNATAKA",AAACB0466ACH015,BABAJI SHIVRAM CLEARING AND CARRIERS PRIVATE L...,...,99.000000,H,NaN,560100.0,'080-41194230,murgesp@tatabp.com,MR. RAMAKRISHNAN,NaN,NULL\r,455
5326,INTKD6,Tughlakabad,4150911,2021-06-01,514068850,RHINE SOLAR LIMITED,"A-75/4, IIND FLOORWAZIRPUR INDUSTRIAL AREA",NEW DELHI,AAECN2245HCH001,NIMIT CARGO MOVERS INDIA PRIVATE LIMITED,...,0.340000,H,NaN,110052.0,'011-45092992,shiv@rhinesolar.in,SHIV MITTAL,NaN,NULL\r,0
5327,INTKD6,Tughlakabad,4150911,2021-06-01,514068850,RHINE SOLAR LIMITED,"A-75/4, IIND FLOORWAZIRPUR INDUSTRIAL AREA",NEW DELHI,AAECN2245HCH001,NIMIT CARGO MOVERS INDIA PRIVATE LIMITED,...,0.360000,H,NaN,110052.0,'011-45092992,shiv@rhinesolar.in,SHIV MITTAL,NaN,NULL\r,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
666742,INNSA1,Nhava Sheva Sea,4514638,2021-06-30,3111010457,ENRICH ENERGY PRIVATE LIMITED,"302, THE ORION, 3RD FLR., KOREGAON, PARK ROAD,...","PUNE, MHRSHTR",NaN,NaN,...,125.895000,H,NaN,411001.0,'918605002352,sanjay.batheja@enrichenergy.com,"CHETAN ZAWAR,VIJAY ZAWAR",NaN,NULL\r,545
666743,INNSA1,Nhava Sheva Sea,4514638,2021-06-30,3111010457,ENRICH ENERGY PRIVATE LIMITED,"302, THE ORION, 3RD FLR., KOREGAON, PARK ROAD,...","PUNE, MHRSHTR",NaN,NaN,...,125.895000,H,NaN,411001.0,'918605002352,sanjay.batheja@enrichenergy.com,"CHETAN ZAWAR,VIJAY ZAWAR",NaN,NULL\r,545
667056,INNSA1,Nhava Sheva Sea,4511784,2021-06-30,314012141,SEVEN GREENS SOLAR SYSTEMS PRIVATE LIMITED,"179 C 20 MIG COLONY OPP MHADA, OFFICE BANDRA EAST","MAHARASHTRA, MAHARASHTRA",NaN,NaN,...,108.000000,H,NaN,400051.0,'919819137727,swapnil.padhye@7greens.in,PRADYOT BORKAR,NaN,NULL\r,450
667504,INNSA1,Nhava Sheva Sea,4509107,2021-06-30,996000402,PREMIER ENERGIES LIMITED,"SY NO 54 PART, G.PULLA REDDY SWEETS, KAKAGUDA,...","SECUNDERBD, TELNGN",NaN,NaN,...,0.570000,H,NaN,500009.0,'919177001518,ramanjulu@premierenergies.com,"SALUJA SURENDERPAL SINGH,KESAR SINGH",NaN,NULL\r,0
671340,INFLT6,Falta Special Economic Zone (SEZ),1001118,2021-06-30,205025056,VIKRAM SOLAR LIMITED,"FALTA SEZ, SECTOR- II24 PARAGANAS S",KOLKATA,NaN,NaN,...,1.626252,NULL,6000001942,743504.0,'919777451565,sujit.choudhury@vikramsolar.com,"JOGINDER PAL DUA,CHUNI LAL DUA",INCCU4,Kolkata Air Cargo\r,0

In [38]:
df['SUPPLIER_NAME'] = df['SUPPLIER_NAME'].str.replace('[^\w\s]','')
df['IMPORTER_NAME'] = df['IMPORTER_NAME'].str.replace('[^\w\s]','')
d1 = pd.read_csv('shipper/shipper_jul.csv')
d1['name'] = d1['name'].str.replace('[^\w\s]','')
d11= pd.Series(d1.id.values,index=d1.name).to_dict()
df['supplier_id'] = df['SUPPLIER_NAME'].map(d11)

In [39]:
df.PRODUCT_DESCRIPTION

3949                             SOLAR MODULE TSM-540 DE 19
4064             PV PANEL,LR4-72HPH-455M/450M-72 CELL LONGI
4065             PV PANEL,LR4-72HPH-455M/450M-72 CELL LONGI
5326      SOLAR CELL POLY 5BB A GARDE 18.0-18.6% EFF, 4....
5327      SOLAR CELL POLY 5BB A GARDE 18.8-18.9% EFF, 4....
                                ...
666742    TSM-545DE19 MBB HALF CELL SOLAR PV MODULE MONO...
666743    TSM-545DE19 MBB HALF CELL SOLAR PV MODULE MONO...
667056    SOLAR MODULES CS3W - MS 450 (BIS REF NO.REGIST...
667504          SOLAR CELLS ,5BB 157X157 MM 18.7% AND ABOVE
671340           BIFACIAL MONO SOLAR CELL (DTL AS PER INV.)
Name: PRODUCT_DESCRIPTION, Length: 577, dtype: object

In [40]:
product = pd.read_csv('product/product_9_july.csv')
product.head()

,id,name,power_rating,created_at,is_active,created_by_id,supplier_id,type_id
0,1,SPR-P3-415-COM,415,2021-05-26 17:50:36.788502,1,1,980,3
1,2,TSM-545DE19,545,2021-06-02 08:47:19.222269,1,1,1033,3
2,3,JKM400M-72H-V,400,2021-06-02 08:49:11.643988,1,1,786,3
3,4,TSM-450DE17M(II),450,2021-06-02 09:14:44.169680,1,1,1033,3
4,5,LR4-72HPH-450M,450,2021-06-03 03:48:12.235411,1,25,839,3

In [43]:
mode_name= product['name']

In [44]:
wp3 = pd.concat([df['PRODUCT_DESCRIPTION'].str.extract('(?P<mode_name>{})'.format("|".join(mode_name)), expand=True).fillna('0')], axis=1)

In [45]:
wp3

             mode_name  1  2  3  4  5
3949                 0  0  0  0  0  0
4064    LR4-72HPH-455M  0  0  0  0  0
4065    LR4-72HPH-455M  0  0  0  0  0
5326                 0  0  0  0  0  0
5327                 0  0  0  0  0  0
...                ... .. .. .. .. ..
666742     TSM-545DE19  0  0  0  0  0
666743     TSM-545DE19  0  0  0  0  0
667056               0  0  0  0  0  0
667504               0  0  0  0  0  0
671340               0  0  0  0  0  0

[577 rows x 6 columns]

In [46]:
df['mode_name']= wp3['mode_name']

In [30]:
df.columns

Index(['CUSH', 'INDIAN_PORT', 'BE_NO', 'IMP_DATE', 'IEC', 'IMPORTER_NAME',
       'ADDRESS', 'CITY', 'CHA_NO', 'CHA_NAME', 'ORIGIN_COUNTRY', 'HS_CODE',
       'PRODUCT_DESCRIPTION', 'QUANTITY', 'UNIT', 'UNIT_VALUE_INR',
       'TOTAL_ASSESSABLE_VALUE_INR', 'UNIT_PRICE_USD', 'TOTAL_ASSESS_USD',
       'TOTAL_DUTY_PAID', 'APPRAISING_GROUP', 'PORT_OF_SHIPMENT',
       'INVOICE_CURRENCY', 'SUPPLIER_NAME', 'SUPPLIER_ADDRESS',
       'INVOICE_UNITPRICE_FC', 'TYPE', 'INVOICE_NO', 'IEC_PIN', 'PHONE_NO',
       'EMAIL', 'CONTACT_PERSON', 'LANDING_PORT_CODE', 'LANDING_PORT_NAME',
       'wp', 'supplier_id', 'import_product_id'],
      dtype='object')

In [47]:



p11= pd.Series(product.id.values,index=product.name).to_dict()
df['import_product_id'] = df['mode_name'].map(d11)
df = df.drop(columns=['mode_name'])

In [56]:
ok=df[['CUSH', 'INDIAN_PORT', 'BE_NO', 'IMP_DATE', 'IEC', 'IMPORTER_NAME',
       'ADDRESS', 'CITY', 'CHA_NO', 'CHA_NAME', 'ORIGIN_COUNTRY', 'HS_CODE',
       'PRODUCT_DESCRIPTION', 'QUANTITY', 'UNIT', 'UNIT_VALUE_INR',
       'TOTAL_ASSESSABLE_VALUE_INR', 'UNIT_PRICE_USD', 'TOTAL_ASSESS_USD',
       'TOTAL_DUTY_PAID', 'APPRAISING_GROUP', 'PORT_OF_SHIPMENT',
       'INVOICE_CURRENCY', 'SUPPLIER_NAME', 'SUPPLIER_ADDRESS',
       'INVOICE_UNITPRICE_FC', 'TYPE', 'INVOICE_NO', 'IEC_PIN', 'PHONE_NO',
       'EMAIL', 'CONTACT_PERSON', 'LANDING_PORT_CODE', 'LANDING_PORT_NAME']]

In [59]:
ok1=df[[ 'PRODUCT_DESCRIPTION','wp', 'supplier_id', 'import_product_id']]

In [60]:
ok1.to_csv("june2.csv" )

In [9]:
df.to_csv('may_total_2021.csv')

In [45]:
df =pd.read_csv('latest upload/2021.csv', encoding = "ISO-8859-1")
df1 =pd.read_csv('latest upload/2020.csv', encoding = "ISO-8859-1")
df2 =pd.read_csv('latest upload/2019.csv', encoding = "ISO-8859-1")

In [46]:
fd = pd.concat([df,df1,df2])
fd.to_csv('total.csv')